"""initial

Revision ID: 7b30c9bac305
Revises:
Create Date: 2026-09-28 11:10:35.351186

"""

from __future__ import annotations

import traceback

import sqlalchemy as sa
from alembic import context, op
from edgy import monkay, run_sync

# revision identifiers, used by Alembic.
revision = "7b30c9bac305"
down_revision = None
branch_labels = None
depends_on = None

force_fields_nullable: list[tuple[str, str]] = []


def upgrade(engine_name: str = "") -> None:
    fn = globals().get(f"upgrade_{engine_name}")
    if fn is not None:
        fn()


def downgrade(engine_name: str = "") -> None:
    fn = globals().get(f"downgrade_{engine_name}")
    if fn is not None:
        fn()


def upgrade_(db_name: str = ""):
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wafrules",
        sa.Column(
            "managed_by",
            sa.String(length=100),
            server_default=sa.text("('')"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "revision",
            sa.SmallInteger(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.String(length=50), autoincrement=False, nullable=False),
        sa.Column("position", sa.SmallInteger(), autoincrement=False, nullable=True),
        sa.Column(
            "stop", sa.Boolean(), server_default=sa.text("0"), autoincrement=False, nullable=False
        ),
        sa.Column(
            "http_methods",
            sa.String(length=100),
            server_default=sa.text("'*'"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("ratelimit_cache", sa.String(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "note", sa.Text(), server_default=sa.text("('')"), autoincrement=False, nullable=False
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("position"),
    )
    op.create_table(
        "wafrulenetworks",
        sa.Column(
            "rule",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("network", sa.String(length=50), autoincrement=False, nullable=False),
        sa.Column("managed_name", sa.String(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "note", sa.Text(), server_default=sa.text("('')"), autoincrement=False, nullable=False
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rule"],
            ["wafrules.id"],
            name="fk_wafrulenetworks_wafrules_rule",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wafrulepaths",
        sa.Column(
            "rule",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("path", sa.Text(), autoincrement=False, nullable=False),
        sa.Column(
            "is_regex",
            sa.Boolean(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("managed_name", sa.String(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "note", sa.Text(), server_default=sa.text("('')"), autoincrement=False, nullable=False
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rule"],
            ["wafrules.id"],
            name="fk_wafrulepaths_wafrules_rule",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wafruleratelimits",
        sa.Column(
            "rule",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("key", sa.Text(), autoincrement=False, nullable=False),
        sa.Column("rate", sa.String(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "decorate_name",
            sa.String(length=50),
            server_default=sa.text("('')"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "matching_groups",
            sa.String(length=100),
            server_default=sa.text("'*'"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "block", sa.Boolean(), server_default=sa.text("0"), autoincrement=False, nullable=False
        ),
        sa.Column(
            "wait", sa.Boolean(), server_default=sa.text("0"), autoincrement=False, nullable=False
        ),
        sa.Column(
            "replace",
            sa.Boolean(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("managed_name", sa.String(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "note", sa.Text(), server_default=sa.text("('')"), autoincrement=False, nullable=False
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rule"],
            ["wafrules.id"],
            name="fk_wafruleratelimits_wafrules_rule",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    if force_fields_nullable and not context.is_offline_mode():
        try:
            with monkay.instance.registry.with_async_env():
                run_sync(
                    monkay.instance.registry.apply_default_force_nullable_fields(
                        force_fields_nullable=force_fields_nullable,
                        filter_db_name="",
                        model_defaults={},
                    )
                )
        except Exception as exc:
            print("failure migrating defaults", exc)
            traceback.print_exception(exc)


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wafruleratelimits")
    op.drop_table("wafrulepaths")
    op.drop_table("wafrulenetworks")
    op.drop_table("wafrules")
    # ### end Alembic commands ###
